version: '3.8'
services:
    site-marcel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app
        restart: unless-stopped